#!/bin/bash
# BSD 3-Clause License
# 
# Copyright (c) 2018-2019, Fabio Jun Takada Chino
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# 
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Include the 
. $(dirname "$0")/common.inc

# Check the parameters
if [ $# -ne 1 ] ; then
	echo "Usage: $0 <user name>"
	exit 1
fi

USERNAME=$1
USER_DIR=$CA_USER_DIR/$USERNAME
USER_KEY=$USER_DIR/privkey.pem
USER_CSR=$USER_DIR/$USERNAME.csr
USER_CER=$USER_DIR/$USERNAME.cer
USER_P12=$USER_DIR/$USERNAME.p12

if [ -d $USER_DIR ]; then
	echo "$USERNAME already exists."
	exit 2
fi

mkdir -p "$USER_DIR"

# Create the user password
USER_PASSWD=$(openssl rand -base64 15)

if openssl genrsa -out $USER_KEY $CA_KEY_SIZE -password pass:$USER_PASSWD ; then
	echo "Private key for the user $USERNAME created."
else
	echo "Unable to create the private key for the user $USERNAME."
	exit 2
fi

if openssl req -new -key $USER_KEY -out $USER_CSR -subj "/CN=$USERNAME/O=$USERNAME/OU=$USERNAME"; then
	echo "CSR for $USERNAME created."
else
	echo "Unable to create the CSR for the user $USERNAME."
	exit 2
fi

cp $USER_CSR $CA_CERT_DIR/$USERNAME.csr
if ./sign $USERNAME ; then
	echo "Certificate signed."
	cp $CA_CERT_DIR/$USERNAME.cer $USER_CER
else
	echo "Unable to sign the certificate."
	exit 1
fi

openssl pkcs12 -export -inkey $USER_KEY -in $USER_CER -out $USER_P12 -password pass:$USER_PASSWD
echo $USER_PASSWD


